server:
  port: 8300

# Spring boot application
spring:
  application:
    name: one-dubbo-consumer

dubbo:
  # Dubbo Application
  # The default value of dubbo.application.name is ${spring.application.name}
  # dubbo.application.name=${spring.application.name}
  application:
    name: one-dubbo-consumer
#  protocol:
#    # Dubbo Protocol
#    name: dubbo
#    ## Random port
#    port: 20880
  # Dubbo Registry
  registry:
    address: zookeeper://192.168.1.112:2181/dubbo
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache

## DemoService version
one:
  service:
    version: 1.0.1