server:
  port: 8001

spring:
  application:
    name: sentinel-demo
  cloud:
    sentinel:
      transport:
        port: 8602
        # sentinel dashboard
        dashboard: localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always