server:
  port: 8201

# Spring boot application
spring:
  application:
    name: one-dubbo-provider

dubbo:
  # Dubbo Application
  # The default value of dubbo.application.name is ${spring.application.name}
  # dubbo.application.name=${spring.application.name}
  application:
    name: one-dubbo-provider
  scan:
    # Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
    base-packages: org.coastline.dubbo.provider.service
  protocol:
    # Dubbo Protocol
    name: dubbo
    # Random port
    port: 9001
  # Dubbo Registry
  registry:
    address: zookeeper://192.168.1.112:2181/dubbo
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache

## DemoService version
one:
  service:
    version: 1.0.1