# 即将废弃
#receivers:
#  otlp:
#    trace:
#      port: 4317
#    metrics:
#      port: 1234
#exporters:
#  kafka:
#    trace:
#      brokers: localhost:9092
#      topic: fairy_trace
#    metrics:
#      brokers:
#      topic:

receivers:
  otlp/trace:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
  otlp/metrics:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4318"
  otlp/log:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4319"


exporters:
  kafka/trace:
    brokers: "localhost:9092"
    topic: "elf_trace"
  kafka/metrics:
    brokers: "localhost:9092"
    topic: "elf_metrics"
  prometheusremotewrite:
    endpoint: "http://localhost:9090/api/v1/write"
  jaeger:
    endpoint: "localhost:14250"
    insecure: true
  otlphttp/metircs:
    endpoint: "http://localhost:8080"

extensions:
  queues:
    mmap:
  health_check:
  jvm:
    endpoint: "0.0.0.0:1776"
  pprof:
    endpoint: "0.0.0.0:1777"

service:
  pipelines:
    traces:
      receivers: [otlp/trace]
      exporters: [jaeger, kafka/trace]
    metrics:
      receivers: [otlp/metrics]
      exporters: [prometheusremotewrite, otlphttp/metircs]





