receivers:
  otlp:
    trace:
      port: 4317
    metrics:
      port: 1234

exporters:
  kafka:
    trace:
      brokers: localhost:9092
      topic: fairy_trace
    metrics:
      brokers:
      topic:

# TODO: 未设计好
extensions:
  server:
    # `standalone`, `cluster`, default `standalone`
    model: cluster
  config:
    # `local`, `remote`, default `local`
    model: remote